# Generated by Django 5.1.1 on 2024-10-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssuranceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Assurance Goals',
                'db_table': 'assurance_goal',
            },
        ),
        migrations.CreateModel(
            name='FairnessApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Fairness Approaches',
                'db_table': 'fairness_approach',
            },
        ),
        migrations.CreateModel(
            name='ProjectLifecycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Project Lifecycle Stages',
                'db_table': 'project_lifecycle_stage',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('assurance_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assurancegoal')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('model_dependency', models.CharField(max_length=255)),
                ('example_use_case', models.TextField()),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.URLField(blank=True)),
                ('software_package', models.URLField(blank=True)),
                ('limitation', models.TextField(blank=True)),
                ('assurance_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assurancegoal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Techniques',
                'db_table': 'technique',
            },
        ),
        migrations.CreateModel(
            name='TechniqueFairnessApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fairness_approach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fairnessapproach')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'db_table': 'technique_fairness_approach',
                'unique_together': {('technique', 'fairness_approach')},
            },
        ),
        migrations.AddField(
            model_name='technique',
            name='fairness_approach',
            field=models.ManyToManyField(blank=True, through='api.TechniqueFairnessApproach', to='api.fairnessapproach'),
        ),
        migrations.CreateModel(
            name='TechniqueProjectLifecycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_lifecycle_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectlifecyclestage')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'db_table': 'technique_project_lifecycle_stage',
                'unique_together': {('technique', 'project_lifecycle_stage')},
            },
        ),
        migrations.AddField(
            model_name='technique',
            name='project_lifecycle_stage',
            field=models.ManyToManyField(blank=True, through='api.TechniqueProjectLifecycleStage', to='api.projectlifecyclestage'),
        ),
        migrations.CreateModel(
            name='TechniqueRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_from', to='api.technique')),
                ('technique_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_to', to='api.technique')),
            ],
            options={
                'db_table': 'technique_relationship',
            },
        ),
        migrations.CreateModel(
            name='TechniqueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'verbose_name_plural': 'Technique Tags',
                'db_table': 'technique_tag',
                'unique_together': {('technique', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='technique',
            name='tags',
            field=models.ManyToManyField(blank=True, through='api.TechniqueTag', to='api.tag'),
        ),
    ]
