# Generated by Django 5.1.6 on 2025-04-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniqueresource',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
