# Generated by Django 5.1.6 on 2025-06-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute_type',
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='technique',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='category',
            name='assurance_goal',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='technique',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='applicable_models',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='model_dependency',
        ),
        migrations.AddField(
            model_name='technique',
            name='related_techniques',
            field=models.ManyToManyField(blank=True, to='api.technique'),
        ),
        migrations.DeleteModel(
            name='AttributeType',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
