services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=tea_user
      - POSTGRES_PASSWORD=tea_password
      - POSTGRES_DB=tea_techniques
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # optional for local development and testing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tea_user -d tea_techniques"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=tea_user
      - DB_PASSWORD=tea_password
      - DB_NAME=tea_techniques
      - DB_PORT=5432
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
      - SECRET_KEY=dev-secret-key
      - DOCKER_ENVIRONMENT=True
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    # For development, uncomment these volume mounts:
    # volumes:
    #   - ./backend:/app
    #   - ./backend/scripts:/app/scripts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_SWAGGER_URL=/swagger/
      - NODE_ENV=production
      - DOCKER_ENV=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - default

volumes:
  postgres_data: