services:
  tea-techniques-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tea-techniques-development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    networks:
      - tea-network

networks:
  tea-network:
    driver: bridge
