services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - USE_SQLITE=True
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://frontend:3000,https://arch-webserver.tailb4d95.ts.net,http://*.ts.net,https://*.ts.net
      - SECRET_KEY=dev-secret-key
      - DOCKER_ENVIRONMENT=True
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - sqlite_data:/app/db_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api
        - NEXT_PUBLIC_SWAGGER_URL=/swagger/
    environment:
      # In Docker environment, use the backend service name for internal requests
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_SWAGGER_URL=/swagger/
      - NODE_ENV=production
      - DOCKER_ENV=true
      - BACKEND_URL=http://backend:8000
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  sqlite_data:
