services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - tea-xai-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  tea-xai-db:
