services:
  - type: web
    name: tea-techniques-backend
    runtime: python
    buildCommand: cd backend && pip install poetry && poetry install --no-dev
    startCommand: cd backend && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tea-techniques-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*.render.com, tea-techniques-frontend.vercel.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://tea-techniques-frontend.vercel.app"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

databases:
  - name: tea-techniques-db
    databaseName: tea_techniques
    plan: free